-- ============================================================
-- USERS TABLE
-- ============================================================

-- Add phone column if it does not already exist
ALTER TABLE users
ADD COLUMN IF NOT EXISTS phone VARCHAR(30);

-- Rename password -> password_hash if password exists
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'users'
          AND column_name = 'password'
    ) THEN
        ALTER TABLE users RENAME COLUMN password TO password_hash;
    END IF;
END $$;


-- ============================================================
-- PRODUCTS TABLE
-- ============================================================

-- Add plant_type column if it does not already exist
ALTER TABLE products
ADD COLUMN IF NOT EXISTS plant_type VARCHAR(100) DEFAULT 'general';


-- ============================================================
-- ORDERS TABLE
-- ============================================================

-- Add payment_method column if it does not already exist
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50);

-- Add payment_status column if it does not already exist
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS payment_status VARCHAR(50) DEFAULT 'pending';

-- Rename status -> order_status if status exists
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'orders'
          AND column_name = 'status'
    ) THEN
        ALTER TABLE orders RENAME COLUMN status TO order_status;
    END IF;
END $$;


-- ============================================================
-- PAGES TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS pages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(150) NOT NULL,
    content TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ============================================================
-- SEED ABOUT PAGE
-- ============================================================

INSERT INTO pages (slug, title, content)
VALUES (
    'about',
    'About GreenLeaf Plants',
    'GreenLeaf Plants is a home-grown plant nursery that ships healthy, hand-picked plants to doorsteps across the country.

We have been growing and caring for plants for over a decade. Every plant that leaves our greenhouse is inspected by hand, packed in breathable material, and shipped with the care guidance it needs to thrive in its new home.

Whether you are setting up your first office desk or redesigning your garden, our team is happy to help you pick the right plant for your light, space and experience.'
)
ON CONFLICT (slug) DO NOTHING;


-- ============================================================
-- SEED CONTACT PAGE
-- ============================================================

INSERT INTO pages (slug, title, content)
VALUES (
    'contact',
    'Contact Us',
    'We would love to hear from you. Our team replies to every message within one working day.

Use the details below to reach us, or drop by the nursery during business hours. Walk-ins are always welcome - no appointment needed.'
)
ON CONFLICT (slug) DO NOTHING;


-- ============================================================
-- SITE SETTINGS TABLE
-- ============================================================

CREATE TABLE IF NOT EXISTS site_settings (
    id SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    footer_text VARCHAR(255) NOT NULL DEFAULT '© 2026 GreenLeaf Plants. All rights reserved.',
    contact_email VARCHAR(255),
    contact_phone VARCHAR(50),
    contact_address TEXT,
    contact_hours VARCHAR(255),
    facebook_url TEXT,
    instagram_url TEXT,
    upi_id VARCHAR(100),
    upi_name VARCHAR(150),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- Insert default settings
INSERT INTO site_settings (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;


-- ============================================================
-- VERIFY
-- ============================================================

SELECT
    table_name,
    column_name,
    data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name IN (
      'users',
      'products',
      'orders',
      'pages',
      'site_settings'
  )
ORDER BY table_name, ordinal_position;