-- ============================================================
-- E-commerce Plant Website - Complete Database Schema
-- PostgreSQL (Supabase)
--
-- Run this entire script in:
-- Supabase Dashboard -> SQL Editor -> New query -> Run
--
-- This version removes the accidental Git diff markers (@ lines)
-- and duplicate column definitions from the previous version.
-- ============================================================

-- ============================================================
-- DROP EXISTING TABLES
-- ============================================================

DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS admin_users CASCADE;
DROP TABLE IF EXISTS users CASCADE;


-- ============================================================
-- USERS TABLE
-- ============================================================

CREATE TABLE users (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ============================================================
-- PRODUCTS TABLE
-- ============================================================

CREATE TABLE products (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    description TEXT,
    price       NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    image_url   TEXT,
    stock       INT NOT NULL DEFAULT 0 CHECK (stock >= 0),
    category    VARCHAR(100),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ============================================================
-- REVIEWS TABLE
-- ============================================================

CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL
                REFERENCES products(id)
                ON DELETE CASCADE,
    user_id     BIGINT NOT NULL
                REFERENCES users(id)
                ON DELETE CASCADE,
    rating      INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (product_id, user_id)
);

CREATE INDEX reviews_product_id_idx
ON reviews (product_id);


-- ============================================================
-- FUNCTION: RENUMBER REVIEWS AFTER DELETE
-- ============================================================

CREATE OR REPLACE FUNCTION renumber_reviews()
RETURNS TRIGGER AS $$
DECLARE
    rid BIGINT;
    nid BIGINT := 1;
BEGIN
    FOR rid IN
        SELECT id
        FROM reviews
        ORDER BY id
    LOOP
        IF rid <> nid THEN
            UPDATE reviews
            SET id = nid
            WHERE id = rid;
        END IF;

        nid := nid + 1;
    END LOOP;

    PERFORM setval(
        'reviews_id_seq',
        COALESCE((SELECT MAX(id) FROM reviews), 0) + 1,
        false
    );

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- REVIEWS DELETE TRIGGER
-- ============================================================

CREATE TRIGGER trg_reviews_renumber
AFTER DELETE ON reviews
FOR EACH STATEMENT
EXECUTE FUNCTION renumber_reviews();


-- ============================================================
-- ORDERS TABLE
-- ============================================================

CREATE TABLE orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT
                    REFERENCES users(id)
                    ON DELETE SET NULL,
    customer_name   VARCHAR(150) NOT NULL,
    customer_phone  VARCHAR(30),
    customer_email  VARCHAR(255),
    address         TEXT NOT NULL,
    city            VARCHAR(100),
    state           VARCHAR(100),
    pincode         VARCHAR(20),
    total_amount    NUMERIC(10,2) NOT NULL DEFAULT 0
                    CHECK (total_amount >= 0),
    status          VARCHAR(50) NOT NULL DEFAULT 'pending',
    order_date      TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ============================================================
-- ORDER ITEMS TABLE
-- ============================================================

CREATE TABLE order_items (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    order_id    BIGINT NOT NULL
                REFERENCES orders(id)
                ON UPDATE CASCADE
                ON DELETE CASCADE,

    product_id  BIGINT NOT NULL
                REFERENCES products(id)
                ON DELETE CASCADE,

    quantity    INT NOT NULL CHECK (quantity > 0),

    price       NUMERIC(10,2) NOT NULL
                CHECK (price >= 0)
);


-- ============================================================
-- FUNCTION: RENUMBER ORDERS AFTER DELETE
-- ============================================================

CREATE OR REPLACE FUNCTION renumber_orders()
RETURNS TRIGGER AS $$
DECLARE
    oid BIGINT;
    nid BIGINT := 1;
BEGIN
    FOR oid IN
        SELECT id
        FROM orders
        ORDER BY id
    LOOP
        IF oid <> nid THEN
            UPDATE orders
            SET id = nid
            WHERE id = oid;
        END IF;

        nid := nid + 1;
    END LOOP;

    PERFORM setval(
        'orders_id_seq',
        COALESCE((SELECT MAX(id) FROM orders), 0) + 1,
        false
    );

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- ORDERS DELETE TRIGGER
-- ============================================================

CREATE TRIGGER trg_orders_renumber
AFTER DELETE ON orders
FOR EACH STATEMENT
EXECUTE FUNCTION renumber_orders();


-- ============================================================
-- ADMIN USERS TABLE
-- ============================================================

CREATE TABLE admin_users (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);


-- ============================================================
-- DEFAULT ADMIN ACCOUNT
--
-- Username: admin
-- Password: admin123
--
-- SHA-256(admin123):
-- 240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9
-- ============================================================

INSERT INTO admin_users (
    username,
    password_hash
)
VALUES (
    'admin',
    '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9'
);


-- ============================================================
-- OPTIONAL SAMPLE USER
-- ============================================================

-- INSERT INTO users (name, email, password)
-- VALUES (
--     'Test User',
--     'test@example.com',
--     'YOUR_PASSWORD_HASH'
-- );


-- ============================================================
-- VERIFY TABLES
-- ============================================================

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
      'users',
      'products',
      'reviews',
      'orders',
      'order_items',
      'admin_users'
  )
ORDER BY table_name;


-- ============================================================
-- VERIFY ADMIN
-- ============================================================

SELECT id, username
FROM admin_users;
