-- ============================================================
-- E-commerce Plant Website - Complete Database Schema
-- PostgreSQL (Supabase)
--
-- Run this entire script in:
-- Supabase Dashboard -> SQL Editor -> New query -> Run
--
-- This version removes the accidental Git diff markers (@ lines)
-- and duplicate column definitions from the previous version.
-- ============================================================

-- ============================================================
-- DROP EXISTING TABLES
-- ============================================================

DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS site_settings CASCADE;
DROP TABLE IF EXISTS pages CASCADE;
DROP TABLE IF EXISTS admin_users CASCADE;
DROP TABLE IF EXISTS users CASCADE;


-- ============================================================
-- USERS TABLE
-- ============================================================

CREATE TABLE users (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    phone         VARCHAR(30),
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ============================================================
-- PRODUCTS TABLE
-- ============================================================

CREATE TABLE products (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    description TEXT,
    price       NUMERIC(10,2) NOT NULL CHECK (price >= 0),
    image_url   TEXT,
    stock       INT NOT NULL DEFAULT 0 CHECK (stock >= 0),
    category    VARCHAR(100),
    plant_type  VARCHAR(100) DEFAULT 'general',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ============================================================
-- PAGES TABLE
--
-- Admin-editable content pages (About, Contact). The storefront
-- fetches these by slug and renders the body text.
-- ============================================================

CREATE TABLE pages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       VARCHAR(50) NOT NULL UNIQUE,
    title      VARCHAR(150) NOT NULL,
    content    TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ============================================================
-- SITE SETTINGS TABLE
--
-- Singleton row (id is pinned to 1 by a CHECK constraint) holding
-- the footer text, contact details, social links and UPI details
-- that the admin can edit from the dashboard.
-- ============================================================

CREATE TABLE site_settings (
    id              SMALLINT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
    footer_text     VARCHAR(255) NOT NULL DEFAULT '© 2026 GreenLeaf Plants. All rights reserved.',
    contact_email   VARCHAR(255),
    contact_phone   VARCHAR(50),
    contact_address TEXT,
    contact_hours   VARCHAR(255),
    facebook_url    TEXT,
    instagram_url   TEXT,
    upi_id          VARCHAR(100),
    upi_name        VARCHAR(150),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO site_settings (id) VALUES (1);


-- ============================================================
-- DEFAULT PAGE CONTENT
-- ============================================================

INSERT INTO pages (slug, title, content)
VALUES (
    'about',
    'About GreenLeaf Plants',
    E'GreenLeaf Plants is a home-grown plant nursery that ships healthy,'
    E' hand-picked plants to doorsteps across the country.\n\n'
    E'We have been growing and caring for plants for over a decade. Every'
    E' plant that leaves our greenhouse is inspected by hand, packed in'
    E' breathable material, and shipped with the care guidance it needs'
    E' to thrive in its new home.\n\n'
    E'Whether you are setting up your first office desk or redesigning'
    E' your garden, our team is happy to help you pick the right plant'
    E' for your light, space and experience.'
);

INSERT INTO pages (slug, title, content)
VALUES (
    'contact',
    'Contact Us',
    E'We would love to hear from you. Our team replies to every message'
    E' within one working day.\n\n'
    E'Use the details below to reach us, or drop by the nursery during'
    E' business hours. Walk-ins are always welcome - no appointment needed.'
);

-- ============================================================
-- REVIEWS TABLE
-- ============================================================

CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL
                REFERENCES products(id)
                ON DELETE CASCADE,
    user_id     BIGINT NOT NULL
                REFERENCES users(id)
                ON DELETE CASCADE,
    rating      INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment     TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

    UNIQUE (product_id, user_id)
);

CREATE INDEX reviews_product_id_idx
ON reviews (product_id);


-- ============================================================
-- FUNCTION: RENUMBER REVIEWS AFTER DELETE
-- ============================================================

CREATE OR REPLACE FUNCTION renumber_reviews()
RETURNS TRIGGER AS $$
DECLARE
    rid BIGINT;
    nid BIGINT := 1;
BEGIN
    FOR rid IN
        SELECT id
        FROM reviews
        ORDER BY id
    LOOP
        IF rid <> nid THEN
            UPDATE reviews
            SET id = nid
            WHERE id = rid;
        END IF;

        nid := nid + 1;
    END LOOP;

    PERFORM setval(
        'reviews_id_seq',
        COALESCE((SELECT MAX(id) FROM reviews), 0) + 1,
        false
    );

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- REVIEWS DELETE TRIGGER
-- ============================================================

CREATE TRIGGER trg_reviews_renumber
AFTER DELETE ON reviews
FOR EACH STATEMENT
EXECUTE FUNCTION renumber_reviews();


-- ============================================================
-- ORDERS TABLE
-- ============================================================

CREATE TABLE orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT
                    REFERENCES users(id)
                    ON DELETE SET NULL,
    customer_name   VARCHAR(150) NOT NULL,
    customer_phone  VARCHAR(30),
    customer_email  VARCHAR(255),
    address         TEXT NOT NULL,
    city            VARCHAR(100),
    state           VARCHAR(100),
    pincode         VARCHAR(20),
    total_amount    NUMERIC(10,2) NOT NULL DEFAULT 0
                    CHECK (total_amount >= 0),
    payment_method  VARCHAR(50),
    payment_status  VARCHAR(50) DEFAULT 'pending',
    order_status    VARCHAR(50) NOT NULL DEFAULT 'pending',
    order_date      TIMESTAMPTZ NOT NULL DEFAULT now()
);


-- ============================================================
-- ORDER ITEMS TABLE
-- ============================================================

CREATE TABLE order_items (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    order_id    BIGINT NOT NULL
                REFERENCES orders(id)
                ON UPDATE CASCADE
                ON DELETE CASCADE,

    product_id  BIGINT NOT NULL
                REFERENCES products(id)
                ON DELETE CASCADE,

    quantity    INT NOT NULL CHECK (quantity > 0),

    price       NUMERIC(10,2) NOT NULL
                CHECK (price >= 0)
);


-- ============================================================
-- FUNCTION: RENUMBER ORDERS AFTER DELETE
-- ============================================================

CREATE OR REPLACE FUNCTION renumber_orders()
RETURNS TRIGGER AS $$
DECLARE
    oid BIGINT;
    nid BIGINT := 1;
BEGIN
    FOR oid IN
        SELECT id
        FROM orders
        ORDER BY id
    LOOP
        IF oid <> nid THEN
            UPDATE orders
            SET id = nid
            WHERE id = oid;
        END IF;

        nid := nid + 1;
    END LOOP;

    PERFORM setval(
        'orders_id_seq',
        COALESCE((SELECT MAX(id) FROM orders), 0) + 1,
        false
    );

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- ORDERS DELETE TRIGGER
-- ============================================================

CREATE TRIGGER trg_orders_renumber
AFTER DELETE ON orders
FOR EACH STATEMENT
EXECUTE FUNCTION renumber_orders();


-- ============================================================
-- ADMIN USERS TABLE
-- ============================================================

CREATE TABLE admin_users (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL
);


-- ============================================================
-- DEFAULT ADMIN ACCOUNT
--
-- Username: admin
-- Password: admin123
--
-- SHA-256(admin123):
-- 240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9
-- ============================================================

INSERT INTO admin_users (
    username,
    password_hash
)
VALUES (
    'admin',
    '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9'
);


-- ============================================================
-- OPTIONAL SAMPLE USER
-- ============================================================

-- INSERT INTO users (name, email, password_hash)
-- VALUES (
--     'Test User',
--     'test@example.com',
--     'YOUR_PASSWORD_HASH'
-- );


-- ============================================================
-- VERIFY TABLES
-- ============================================================

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
      'users',
      'products',
      'reviews',
      'orders',
      'order_items',
      'admin_users',
      'pages',
      'site_settings'
  )
ORDER BY table_name;


-- ============================================================
-- VERIFY ADMIN
-- ============================================================

SELECT id, username
FROM admin_users;
